%Up Counter, iterable

function [COUNTER_UP_OUTPUT]=COUNTER_UP(COUNTER_UP_INPUT)
%INPUT FORMAT (COUNTER_UP_CU_OLD,COUNTER_UP_CU,COUNTER_UP_CV,COUNTER_UP_PV,COUNTER_UP_RESET,COUNTER_UP_Q)

%Counter reset
if COUNTER_UP_INPUT(5)==1
	COUNTER_UP_INPUT(6)=0;
	COUNTER_UP_INPUT(3)=0;
	COUNTER_UP_INPUT(4)=0;
	COUNTER_UP_INPUT(1)=COUNTER_UP_INPUT(2);
else


    %Count up

    if COUNTER_UP_INPUT(2)==1 & COUNTER_UP_INPUT(1)==0
        COUNTER_UP_INPUT(3)=COUNTER_UP_INPUT(3)+1;
    end


    %Predefined value reached

    if COUNTER_UP_INPUT(3)>=COUNTER_UP_INPUT(4)
        COUNTER_UP_INPUT(6)=1;
    else
        COUNTER_UP_INPUT(6)=0;
    end
end


%Update diferential values

COUNTER_UP_INPUT(1)=COUNTER_UP_INPUT(2);


%Write ouput vector

COUNTER_UP_OUTPUT=COUNTER_UP_INPUT;
%OUTPUT FORMAT (COUNTER_UP_CU_OLD,COUNTER_UP_CU,COUNTER_UP_CV,COUNTER_UP_PV,COUNTER_UP_RESET,COUNTER_UP_Q)
