%Down Counter, iterable

function [COUNTER_DOWN_OUTPUT]=COUNTER_DOWN(COUNTER_DOWN_INPUT)
%INPUT FORMAT (COUNTER_DOWN_CD_OLD,COUNTER_DOWN_CD,COUNTER_DOWN_INPUT(3),COUNTER_DOWN_INPUT(4),COUNTER_UP_LOAD,COUNTER_UP_Q)

%Counter load
if COUNTER_DOWN_INPUT(5)==1
	COUNTER_DOWN_INPUT(6)=0;
	COUNTER_DOWN_INPUT(3)=COUNTER_DOWN_INPUT(4);
	COUNTER_DOWN_INPUT(1)=COUNTER_DOWN_INPUT(2);
else


    %Count down

    if COUNTER_DOWN_INPUT(2)==1 & COUNTER_DOWN_INPUT(1)==0 
        COUNTER_DOWN_INPUT(3)=COUNTER_DOWN_INPUT(3)-1;
    end


    %Predefined value reached

    if COUNTER_DOWN_INPUT(3)<=0
        COUNTER_DOWN_INPUT(6)=1;
    else
        COUNTER_DOWN_INPUT(6)=0;
    end
end


%Update diferential values

COUNTER_DOWN_INPUT(1)=COUNTER_DOWN_INPUT(2);


%Write ouput vector

COUNTER_DOWN_OUTPUT=COUNTER_DOWN_INPUT;
%OUTPUT FORMAT (COUNTER_DOWN_CD_OLD,COUNTER_DOWN_CD,COUNTER_DOWN_INPUT(3),COUNTER_DOWN_INPUT(4),COUNTER_UP_LOAD,COUNTER_UP_Q)
