%Timer, iterable

function [TIMER_OUTPUT]=TIMER_ON(CLOCK_IN,TIMER_INPUT)
%INPUT FORMAT: IN_OLD,IN,ET,PT,TARGET_TIME_ABSOLUTE,Q


if TIMER_INPUT(1)==0 & TIMER_INPUT(2)==1  
    TIMER_INPUT(6)=0;  
    TIMER_INPUT(3)=0;
	TIMER_INPUT(5)=CLOCK_IN+TIMER_INPUT(4);
end

if TIMER_INPUT(1)==1 & TIMER_INPUT(2)==0
    TIMER_INPUT(3)=0;
    TIMER_INPUT(6)=0;
	TIMER_INPUT(5)=0;
end

%Update elapsed tim
if TIMER_INPUT(2)==1
    TIMER_INPUT(3)=CLOCK_IN+TIMER_INPUT(4)-TIMER_INPUT(5);
end

if TIMER_INPUT(4)>0 & (CLOCK_IN>=TIMER_INPUT(5)) & TIMER_INPUT(2)==1  
   TIMER_INPUT(6)=1;
else
   TIMER_INPUT(6)=0;
end


%Update diferential values
TIMER_INPUT(1)=TIMER_INPUT(2);

TIMER_OUTPUT=TIMER_INPUT;
%OUTPUT FORMAT: IN_OLD,IN,ET,PT,START_TIME_ABSOLUTE,Q